apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
secretGenerator:
- name: mysql-pass
  literals:
  - password=VMware1!
resources:
  - namespace.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
